services:
  server:
    build:
      context: server
    ports:
      - 8000:8000
    depends_on:
      client:
        condition: service_healthy
  client:
    build:
      context: client
    ports:
      - 8001:80